### PR TITLE
Testing | Improving databases: password fix and type selection

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
I do not understand why the upgrades are failing.

**Comment by alexAubin** [comment]
Or maybe because during the preliminary install we have : 


 > Preliminary install...

```
Running: yunohost app install --force /app_folder -a "with_mysql=0&password=SuperDuper_StrongPassw0rd&domain=&path=/site&with_sftp=True&init_main_permission=visitors&phpversion=8.0"
```

with `domain=` (empty),  but i'm not sure to understand why that happens, and how it does even accept to install with an empty domain arg ...?

**Comment by tituspijean** [comment]
@alexAubin the issue was that the "test_upgrade_from" path argument was defaulting to `/site` while the test itself expected the app to be installed on `/`. There's a mishap in the package checker. 😇 

All good for me here in any case.

**Review by alexAubin — APPROVED** [review]

**Pull request merged**
