### PR TITLE
Force https

### PR DESCRIPTION
**Pull request by anmol26s**
## Problem

Every time this app is installed, the nginx file needs to edited to force the https. This should be there by default in the nginx config file.

## Solution

Add a redirection from "http://" to "https://" in nginx.conf.

## PR Status

Work finished. Could be reviewed and tested.

## Validation
*Micro-decision*
- [x] **Code review** : 
- [x] **Approval (LGTM)** :

### CODE REVIEW

**Comment by frju365** [comment]
@maniackcrudelis : Can we pass this PR in micro-decision ?

**Comment by JimboJoe** [comment]
I agree with the micro-decision, but I'd rather have correct spacings... 😉

**Comment by frju365** [comment]
yes, true. Perhaps add correct indentation, @anmol26s.

**Comment by anmol26s** [comment]
@JimboJoe @frju365  done
Thanks

**Comment by frju365** [comment]
ok. Let's merge it.

**Comment by anmol26s** [comment]
The testing is ok.

**Comment by anmol26s** [comment]
Can we merge in the master? This has been waiting for long time now.

**Pull request merged**
