### PR TITLE
Custom PHP version

### LINKED ISSUE #71: Indicate that the app supports PHP webapps
Seems that for the creator of the project "Webapp" and "PHP Webapp" are the same thing

I'd suggest that at least the README indicates that this is for PHP and which version of PHP will be available

### PR DESCRIPTION
**Pull request by ericgaspar**
- Add the choice of PHP version to install :  https://github.com/YunoHost-Apps/my_webapp_ynh/issues/69
- Closes #71

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by tituspijean — COMMENTED** [review]
Maybe we should add test suites to try the other PHP versions too?

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
I am not too fan of using "php_custom" everything, I think we could have stuck with `phpversion`.

**Comment by ericgaspar** [comment]
I agree with `php_custom` not being a great var name but I wanted to avoid the confusion with `phpversion` being automagically replaced with 7.3 by the core... (feel free to pick a more appropriate `custom_var`)

**Comment by tituspijean** [comment]
Tested on my end, I think it works if we keep `phpversion` as variable name.

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Should we remove "Upgrade from May 26, 2019" test? Somehow its installation (before even upgrading) is flagged as failure.

**Comment by tituspijean** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Review by tituspijean — APPROVED** [review]
Cheating a bit since I pushed some commits, but LGTM.

**Comment by yalh76** [comment]
Would be cool to be able to choose without PHP :)

**Review by tituspijean — CHANGES_REQUESTED** [review]
- [x] Add the option to *not* use PHP

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Review by yalh76 — APPROVED** [review]
Marvelous

**Pull request merged**
