### PR TITLE
Testing: Use sftp.app group from 4.2 to manage sftp access, + fix permissions

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

- upcoming 4.2 will break sftp access
- no chmod o-rwx on $final_path

## Solution

- Add the system user to sftp.app when relevant
- Fix $final_path's permissions

## PR Status

- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
(Test's gonna fail because it requires yunohost >= 4.2.3)

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
!testme

**Pull request merged**
